version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo_mongo_db
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  api:
    depends_on:
      - mongodb
    container_name: todo_api
    build: ./api
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend

  client:
    container_name: todo_client
    env_file: ./.env
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    networks:
      - backend

volumes:
  db:
networks:
  backend:
